### PR TITLE
Landing Page

### PR DESCRIPTION
**Pull request by hebronh**
#62

### CODE REVIEW

**Review by yashaswini-slu — CHANGES_REQUESTED** [review]
As a user, i have see the landing-page has my main page.
When application starts show user the landing page, form there you have to direct it to the simulation creation page.

**Review by yashaswini-slu — CHANGES_REQUESTED** [review]
Create simulation option is not a navigation page.It should not be in navigation bar.
It should be in main page.
Improve the look and feel of the page.
Screenshot 2024-03-16 at 21 02 15

**Review by yashaswini-slu — CHANGES_REQUESTED** [review]
About us should be link, we should always have link in navigation bar
Screenshot 2024-03-18 at 11 20 16

**Review by yashaswini-slu — CHANGES_REQUESTED** [review]
Screenshot 2024-03-18 at 11 20 24

the create button looks like its disabled. Improve it

**Comment by hebronh** [comment]
> Screenshot 2024-03-18 at 11 20 24
> the create button looks like its disabled. Improve it

do i just keep the About Us but remove the surrounding button? aside from that what should be changed?
Secondly the create simulation button is working on my end, I do not know why it is disabled.

**Comment by hebronh** [comment]
> > Screenshot 2024-03-18 at 11 20 24
> > the create button looks like its disabled. Improve it
> 
> do i just keep the About Us but remove the surrounding button? aside from that what should be changed? Secondly the create simulation button is working on my end, I do not know why it is disabled.

About Us is now a link instead of button. Shall I simply change the button color? Is the color what makes it appear to be disabled ?

**Comment by hebronh** [comment]
Screenshot 2024-03-18 at 12 42 54 PM
new design

**Review by yashaswini-slu — APPROVED** [review]

**Pull request merged**
