### PR TITLE
Switched names to the desired version

### PR DESCRIPTION
**Pull request by sr259**
Made the changes in the MissionConfiguration.jsx, EnvironmentConfiguration.jsx, simulation_taskmanager.py

### CODE REVIEW

**Review by yashaswini-slu — CHANGES_REQUESTED** [review]
There is error in the file
Screenshot 2023-11-03 at 17 14 59

**Review by yashaswini-slu — CHANGES_REQUESTED** [review]
wind type implementation is modified which is not required

**Comment by sr259** [comment]
could you elaborate a little bit more, I don't think I changed anything when it comes to the wind type

**Review by yashaswini-slu — CHANGES_REQUESTED** [review]
Resolve merge conflicts

**Review by yashaswini-slu — APPROVED** [review]

**Pull request merged**
