### PR TITLE
apiCall for Folders

### PR DESCRIPTION
**Pull request by kalyus**

### CODE REVIEW

**Comment by kalyus** [comment]
Here is the example output. This method is a little different from the way that was suggested, but I think this is cleaner and allows the content to be better organized.

{
    '.txt': [
        {
            "name": "example1.txt",
            "parent": "FolderA",
            "content": "This is the content of example1.txt."
        },
        {
            "name": "example2.txt",
            "parent": "FolderB",
            "content": "This is the content of example2.txt."
        }
    ],
    '.html': [
        {
            "name": "index.html",
            "parent": "FolderA",
            "content": "aGVsbG8gd29ybGQ=..."  # Abbreviated base64
        }
    ],
    '.png': [
        {
            "name": "image1.png",
            "parent": "FolderB",
            "content": "iVBORw0KGgoAAAANSUhEUgAAA... "  # Abbreviated base64
        },
        {
            "name": "image2.png",
            "parent": "FolderC",
            "content": "iVBORw0KGgoAAAANSUhEUgAAA... "  # Abbreviated base64
        }
    ]
}

**Comment by kalyus** [comment]
The other way is also done, but is extremely messy due to the base64 code being converted to its string format. It makes it hard to find and access the content of the TXT files. However if desired, I can make another PR with that implementation.

**Review by yashaswini-slu — CHANGES_REQUESTED** [review]
It should be listed based on Monitors.

**Review by yashaswini-slu — COMMENTED** [review]
Screenshot 2024-04-01 at 13 06 07

**Review by yashaswini-slu — CHANGES_REQUESTED** [review]
Screenshot 2024-04-01 at 13 05 19
Screenshot 2024-04-01 at 13 05 12

**Review by yashaswini-slu — CHANGES_REQUESTED** [review]
port number modified, it should be 5000

**Review by yashaswini-slu — APPROVED** [review]

**Pull request merged**
