### PR TITLE
add loader in report dashboard

### PR DESCRIPTION
**Pull request by Alhajideen**
### What I have achieved in this milestone:

- I have added a loader in the report dashboard that only comes up when the reports are loading(placeholder)
- Do not show the snackbar(No report found) until the reports is successfully loaded
- Do not show the button `Return to Home` until the reports are done loading
However;
With present logic, I think the loader on the landing page is necessary as the reports are also being fetched and displayed on the homepage(if there are reports). However, I have adjusted design and removed one of the duplicated button saying `Create Simulation`
Please kindly review.
Thanks

### CODE REVIEW

**Review by mohamdlog — CHANGES_REQUESTED** [review]
I just tested everything and it looks great – excellent work! I do have one request, though. I noticed that while the landing page is loading, the "Welcome to Drone World!" greeting disappears and is replaced solely by the loading UI. This isn’t something you did; I only picked up on it because your version has both the acceptance report and the loading UI displayed underneath. Could you configure it so that the landing page still shows the greeting even while it’s loading? Also, if possible, could you align the greeting and the acceptance report so they both appear in the same spot?

**Comment by Alhajideen** [comment]
> I just tested everything and it looks great – excellent work! I do have one request, though. I noticed that while the landing page is loading, the "Welcome to Drone World!" greeting disappears and is replaced solely by the loading UI. This isn’t something you did; I only picked up on it because your version has both the acceptance report and the loading UI displayed underneath. Could you configure it so that the landing page still shows the greeting even while it’s loading? Also, if possible, could you align the greeting and the acceptance report so they both appear in the same spot?

**Comment by Alhajideen** [comment]
Thank you @mohamdlog ,
I will do that.
Thanks

**Review by mohamdlog — CHANGES_REQUESTED** [review]
Looks good! I really like your idea about having the welcome message stickied at the top. However, I did notice something: the welcome message and the` Acceptance Reports` section don’t appear to be equally centered. My guess is that this issue stems from the padding added by the Home button.
Screenshot 2024-11-03 123927

**Comment by Alhajideen** [comment]
The problem is due to the Home Icon on the extreme right, it pushes the header to the left. However, this icon is only useful when it is on the report dashboard and not when already on the homepage. I have fixed it to only show this icon on the report dashboard page.
Thanks

**Review by mohamdlog — APPROVED** [review]
"Great work on this! Everything looks solid, and I appreciate the attention to detail.

**Pull request merged**
