### PR TITLE
Battery Monitor Commit

### PR DESCRIPTION
**Pull request by Hoshi-Okami**
Fix: Issue #21

what was changed: Ability for the user to input current battery capacity details of the drone.

why: So that the simulator can track the battery deails of the drone.

how was it changed:
- added a new 'battery' area in test configuration 
- inserted description stating - 'Test whether the drone's battery dropped below the certain percentage'
- added a status option to enable or disable text box of the battery capacity detail
- inserted a text box that only accepts numbers between 0-100 that is tracked with the battery monitor variable

### CODE REVIEW

**Review by Damerson1 — COMMENTED** [review]
The code looks fine and works as intended. The only thing I see is that there is not an area to enter the battery percent when it falls below a certain value.

**Review by mohamdlog — CHANGES_REQUESTED** [review]
The PR is solid, but it would be helpful to add a way for users to input a target battery percentage for testing failure conditions. This would complement the current battery capacity input and make the feature more complete. Overall, nice work!

**Review by mohamdlog — CHANGES_REQUESTED** [review]
It seems the pull request has a bug where the Battery Capacity (%) and Target Failure Percentage (%) fields are improperly linked, causing both fields to display the same value. Additionally, the Target Failure Percentage field is locked and cannot be edited independently, which needs to be fixed to allow separate input for each field.

**Review by mohamdlog — APPROVED** [review]
Great job! Excellent commitment to resolving issues.

**Pull request merged**
